# Form implementation generated from reading ui file 'ManufacturerStatusDetails.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ManufacturerStatusDetails(object):
    def setupUi(self, ManufacturerStatusDetails):
        ManufacturerStatusDetails.setObjectName("ManufacturerStatusDetails")
        ManufacturerStatusDetails.resize(596, 539)
        ManufacturerStatusDetails.setStyleSheet("background-color:#D0DBE3")
        self.centralwidget = QtWidgets.QWidget(ManufacturerStatusDetails)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("QLineEdit{background-color:white;}\n"
"\n"
"\n"
"QLabel{color: #8FA0C9;}\n"
"\n"
"QComboBox{background-color:white;}\n"
"\n"
"QPushButton{border:1px solid white; border-radius:10px;}\n"
"\n"
"")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 578, 521))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#8FA0C9")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMaximumSize(QtCore.QSize(300, 100))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Downloads/MicrosoftTeams-image.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_4.setStyleSheet("QLabel {color: #8FA0C9;}\n"
"\n"
"QComboBox{background-color:white}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setMaximumSize(QtCore.QSize(197, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.comboBox_ManufacturerStatus = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_ManufacturerStatus.setMaximumSize(QtCore.QSize(50, 16777215))
        self.comboBox_ManufacturerStatus.setObjectName("comboBox_ManufacturerStatus")
        self.horizontalLayout_3.addWidget(self.comboBox_ManufacturerStatus)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_2.setStyleSheet("QLineEdit{background-color:white;}\n"
"\n"
"QTextEdit{background-color:white;}\n"
"\n"
"QPushButton{background-color:white;border: 2px solid black; border-radius:10px;}\n"
"\n"
"QLabel{color: #8FA0C9;}\n"
"\n"
"QComboBox{background-color:white;}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.horizontalLayout_4.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_5.addWidget(self.lineEdit_2)
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_7.setStyleSheet("QPushButton{color:#F27E14;}\n"
"\n"
"QPushButton::hover{border: solid black; background-color:white;}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton = QtWidgets.QPushButton(self.frame_8)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_8.addWidget(self.pushButton)
        self.horizontalLayout_7.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(140, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_9.addWidget(self.pushButton_2)
        self.horizontalLayout_7.addWidget(self.frame_9)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_3.setStyleSheet("QPushButton{color:#F27E14;}\n"
"\n"
"QPushButton::hover{border: solid black; background-color:white;}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_Submit = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_Submit.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_Submit.setMaximumSize(QtCore.QSize(90, 16777215))
        self.pushButton_Submit.setObjectName("pushButton_Submit")
        self.horizontalLayout_2.addWidget(self.pushButton_Submit)
        self.pushButton_ClearForm = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_ClearForm.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_ClearForm.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_ClearForm.setObjectName("pushButton_ClearForm")
        self.horizontalLayout_2.addWidget(self.pushButton_ClearForm)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        ManufacturerStatusDetails.setCentralWidget(self.centralwidget)

        self.retranslateUi(ManufacturerStatusDetails)
        QtCore.QMetaObject.connectSlotsByName(ManufacturerStatusDetails)

    def retranslateUi(self, ManufacturerStatusDetails):
        _translate = QtCore.QCoreApplication.translate
        ManufacturerStatusDetails.setWindowTitle(_translate("ManufacturerStatusDetails", "Manufacturer Status Details"))
        self.label.setText(_translate("ManufacturerStatusDetails", "Manufacturer Status"))
        self.label_4.setText(_translate("ManufacturerStatusDetails", "Select Manufacturer Status Code to edit:"))
        self.label_3.setText(_translate("ManufacturerStatusDetails", "Manufacturer Status Code:"))
        self.label_5.setText(_translate("ManufacturerStatusDetails", "Add Manufacturer Status:"))
        self.pushButton.setText(_translate("ManufacturerStatusDetails", "Update Manufacturer Status"))
        self.pushButton_2.setText(_translate("ManufacturerStatusDetails", "Add Manufacturer Status"))
        self.pushButton_Submit.setText(_translate("ManufacturerStatusDetails", "Save Changes"))
        self.pushButton_ClearForm.setText(_translate("ManufacturerStatusDetails", "Delete Manufacturer Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ManufacturerStatusDetails = QtWidgets.QMainWindow()
    ui = Ui_ManufacturerStatusDetails()
    ui.setupUi(ManufacturerStatusDetails)
    ManufacturerStatusDetails.show()
    sys.exit(app.exec())
