# Form implementation generated from reading ui file 'Promotion.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Promotion(object):
    def setupUi(self, Promotion):
        Promotion.setObjectName("Promotion")
        Promotion.resize(605, 343)
        Promotion.setStyleSheet("background-color:#D0DBE8")
        self.centralwidget = QtWidgets.QWidget(Promotion)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("QPushButton{border:1px solid white; border-radius:10px;}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 585, 323))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#8FA0C9")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMaximumSize(QtCore.QSize(300, 100))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Downloads/MicrosoftTeams-image.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 115))
        self.frame_2.setStyleSheet("QLineEdit{background-color:white;}\n"
"\n"
"QPushButton{background-color:white;border: 2px solid black; border-radius:10px;}\n"
"\n"
"QLabel{color: #8FA0C9;}\n"
"\n"
"QComboBox{background-color:white;}\n"
"\n"
"QTextEdit{background-color:white;}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setMaximumSize(QtCore.QSize(110, 40))
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.textEdit_PromotionDescription = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_PromotionDescription.setMaximumSize(QtCore.QSize(170, 50))
        self.textEdit_PromotionDescription.setObjectName("textEdit_PromotionDescription")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textEdit_PromotionDescription)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.lineEdit_DiscountAmount = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_DiscountAmount.setMaximumSize(QtCore.QSize(160, 180))
        self.lineEdit_DiscountAmount.setText("")
        self.lineEdit_DiscountAmount.setMaxLength(100)
        self.lineEdit_DiscountAmount.setObjectName("lineEdit_DiscountAmount")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_DiscountAmount)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.comboBox_SeasonID = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_SeasonID.setMaximumSize(QtCore.QSize(50, 70))
        self.comboBox_SeasonID.setObjectName("comboBox_SeasonID")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBox_SeasonID)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 115))
        self.frame_3.setStyleSheet("QPushButton{color:#F27E14;}\n"
"\n"
"QPushButton::hover{border: solid black; background-color:white;}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(80, 10))
        self.pushButton.setObjectName("pushButton")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pushButton_2)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        Promotion.setCentralWidget(self.centralwidget)

        self.retranslateUi(Promotion)
        QtCore.QMetaObject.connectSlotsByName(Promotion)

    def retranslateUi(self, Promotion):
        _translate = QtCore.QCoreApplication.translate
        Promotion.setWindowTitle(_translate("Promotion", "Promotion"))
        self.label.setText(_translate("Promotion", "New Promotion Form"))
        self.label_3.setText(_translate("Promotion", "Promotion Description:"))
        self.label_4.setText(_translate("Promotion", "Discount Amount:"))
        self.label_5.setText(_translate("Promotion", "Season ID:"))
        self.pushButton.setText(_translate("Promotion", "Clear Form"))
        self.pushButton_2.setText(_translate("Promotion", "Submit Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Promotion = QtWidgets.QMainWindow()
    ui = Ui_Promotion()
    ui.setupUi(Promotion)
    Promotion.show()
    sys.exit(app.exec())
