# Form implementation generated from reading ui file 'PromotionDetails.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PromotionDetails(object):
    def setupUi(self, PromotionDetails):
        PromotionDetails.setObjectName("PromotionDetails")
        PromotionDetails.resize(496, 433)
        PromotionDetails.setStyleSheet("background-color:#D0DBE8")
        self.centralwidget = QtWidgets.QWidget(PromotionDetails)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("QLineEdit{background-color:white;}\n"
"\n"
"\n"
"QLabel{color: #8FA0C9;}\n"
"\n"
"QComboBox{background-color:white;}\n"
"\n"
"QPushButton{border:1px solid white; border-radius:10px;}\n"
"\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 476, 413))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#8Fa0c9")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMaximumSize(QtCore.QSize(300, 100))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Downloads/MicrosoftTeams-image.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_4.setStyleSheet("QPushButton{color:#F27E14;}\n"
"\n"
"QPushButton::hover{border: solid black; background-color:white;}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setMaximumSize(QtCore.QSize(155, 16777215))
        self.label_6.setStyleSheet("color:#")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.comboBox_PromotionCode = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_PromotionCode.setMaximumSize(QtCore.QSize(55, 16777215))
        self.comboBox_PromotionCode.setObjectName("comboBox_PromotionCode")
        self.horizontalLayout_3.addWidget(self.comboBox_PromotionCode)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButton_3.setStyleSheet("QPushButton{color:#F27E14;}\n"
"\n"
"QPushButton::hover{border: solid black; background-color:white;}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_2.setStyleSheet("QTextEdit{background-color:white;}\n"
"\n"
"QLineEdit{background-color:white;}\n"
"\n"
"QPushButton{background-color:white;border: 2px solid black; border-radius:10px;}\n"
"\n"
"QLabel{color: #8FA0C9;}\n"
"\n"
"QComboBox{background-color:white;}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.lineEdit_DiscountAmount = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_DiscountAmount.setMaximumSize(QtCore.QSize(115, 16777215))
        self.lineEdit_DiscountAmount.setText("")
        self.lineEdit_DiscountAmount.setMaxLength(25)
        self.lineEdit_DiscountAmount.setObjectName("lineEdit_DiscountAmount")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_DiscountAmount)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.comboBox_SeasonID = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_SeasonID.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_SeasonID.setObjectName("comboBox_SeasonID")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBox_SeasonID)
        self.textEdit_PromotionDescription = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_PromotionDescription.setMaximumSize(QtCore.QSize(200, 50))
        self.textEdit_PromotionDescription.setObjectName("textEdit_PromotionDescription")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textEdit_PromotionDescription)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_3.setStyleSheet("QPushButton{color:#F27E14;}\n"
"\n"
"QPushButton::hover{border: solid black; background-color:white;}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(110, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        PromotionDetails.setCentralWidget(self.centralwidget)

        self.retranslateUi(PromotionDetails)
        QtCore.QMetaObject.connectSlotsByName(PromotionDetails)

    def retranslateUi(self, PromotionDetails):
        _translate = QtCore.QCoreApplication.translate
        PromotionDetails.setWindowTitle(_translate("PromotionDetails", "Promotion Details"))
        self.label.setText(_translate("PromotionDetails", "Promotion Details"))
        self.label_6.setText(_translate("PromotionDetails", "Select Promotion Code to edit:"))
        self.pushButton_3.setText(_translate("PromotionDetails", "Select Promotion Code"))
        self.label_3.setText(_translate("PromotionDetails", "Promotion Description:"))
        self.label_4.setText(_translate("PromotionDetails", "Discount Amount:"))
        self.label_5.setText(_translate("PromotionDetails", "Season ID:"))
        self.pushButton.setText(_translate("PromotionDetails", "Save Changes"))
        self.pushButton_2.setText(_translate("PromotionDetails", "Delete Promotion"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PromotionDetails = QtWidgets.QMainWindow()
    ui = Ui_PromotionDetails()
    ui.setupUi(PromotionDetails)
    PromotionDetails.show()
    sys.exit(app.exec())
